### ISSUE TITLE
mvn aggregate:serenity doesn't work in grid setup

### ISSUE THREAD

**Issue by vikramvi** [serenity-bdd/serenity-maven-plugin#14]
In case of grid setup , I had to explicitly execute mvn aggregate:serenity to generate index.html.

It does work only in case of single browser scenario.

Please clarify if this is bug or needs to be handled in different way for Grid setup

**Comment by YamStranger** [comment]
Hello @vikramvi. Thanks for creating this issue. 

Please add more details to help you. Also we updated documentation (and your question about flow for aggregation should be there) and may be you will find answer to your question under [this chapter](http://thucydides.info/docs/serenity-staging/#_running_serenity_tests_in_parallel_batches)

If you feel that you already find solution, or issue fixed - please close this issue. 

Thanks a lot!

**Comment by YamStranger** [comment]
It seems this already fixed or not and issue at all.
