### ISSUE TITLE
Is there a way to call Aggregator from java code instead of calling it from Pom.xml

### ISSUE THREAD

**Issue by prak0628** [serenity-bdd/serenity-maven-plugin#17]
In my group , we are using serenity with JBehave . We are trying to create an executable jar for our functional testers so that they can double click on the jar and execute the test.For the same i am not able to call the aggregate phase since the executable jar does not have a pom.xml to do so.
May i please know is there any way for us to create JSON reports and the call the aggregate method via java code for eg: In @afterStories annotation. Please advice on this.

**Comment by johndeverall** [comment]
@prak0628 I don't know the answer myself, but I have been wondering as I'd like to do the same thing. There's about 5 or 6 files in the maven plugin it seems, and you might be quicker than I am at figuring out which serenity code it calls. 

https://github.com/serenity-bdd/serenity-maven-plugin

**Comment by YamStranger** [comment]
Hello @prak0628. 

Take a look at [gradle plugin](https://github.com/serenity-bdd/serenity-core/blob/master/serenity-gradle-plugin/src/main/groovy/net/serenitybdd/plugins/gradle/SerenityPlugin.groovy#L40), may be source of it will be helpful for you. 

main line there is:

```
reporter.generateReportsForTestResultsFrom(reportDirectory)
```

**Comment by YamStranger** [comment]
Hi @prak0628 

If you fell that you find answer for your question - please close this issue. 
Thanks a lot!

**Comment by prak0628** [comment]
Hi Yam,
Still the issue is not resolved and working on it.

**Comment by YamStranger** [comment]
@prak0628 if you have some additional question - just ask. 

Thanks!

**Comment by prak0628** [comment]
Iam unable to use the Gradle plug in since it needs a Project object from the Gradle API. But not sure how i can download the dependency for org.gardle.api.Project . Please let me know if you have any info.

**Comment by YamStranger** [comment]
@prak0628 you don't need gradle at all. Just use it as example of code, where reporter class are used - not more.
```
reporter.generateReportsForTestResultsFrom(reportDirectory)
```
It is simple class, and can be separately used from generating reports.

The same lines you will find in maven-plugin and ant-plugin. 

We have two types of reports: 
1) when you run tests with serenity bdd, it creates some reports in xml, html formats, with unique names
2) after that reporter class used to aggregate those reports from first step and create some statistics and so on.

**Comment by prak0628** [comment]
@YamStranger 
I do understand i have to use the above line of code.But in order to create an object for "HtmlAggregateStoryReporter" , i have to create it with mentioning Project(org.gradle.api.Project) while instantiating which iam unable to find.

**Comment by YamStranger** [comment]
@prak0628, I don't understand you

I see that you need only project name (it is string), and folder with reports. Nothing more ( 

May be we are talking about different sings, can you provide some example where you can try to use this class [HtmlAggregateStoryReporter](https://github.com/serenity-bdd/serenity-core/blob/8a21a9f2ca827b9ade4661f724f3f5c7a5e7160b/serenity-core/src/main/java/net/thucydides/core/reports/html/HtmlAggregateStoryReporter.java) ?

**Comment by YamStranger** [comment]
It seems that this problem already solved.

**Comment by karkhile** [comment]
@YamStranger @prak0628 , if you guys know the solution could you please help me because even I am looking for this

**Comment by wakaleo** [comment]
As mentioned in the above thread, take a look at the Maven or Gradle plugin source code (https://github.com/serenity-bdd/serenity-maven-plugin) - generating the reports programatically is straightforward and only needs a dependency on serenity-core.
