### ISSUE TITLE
Wrong aggregation result with multiple Test class

### ISSUE THREAD

**Issue by dwursteisen** [serenity-bdd/serenity-maven-plugin#37]
Hello, 

I try to run multiple test class in parallele using maven failsafe plugins. 
When trying to achieve this, I split my Test class into several test class.

ie: 

`MyTest.java` with `@Cucumber.Options(features="/features")`  becomes :

- `MyATest.java` with `@Cucumber.Options(features="/features/a")`
- `MyBTest.java` with `@Cucumber.Options(features="/features/b")`
- `MyCTest.java` with `@Cucumber.Options(features="/features/c")`
- ...

The aggregation result seems to be good on the first sight (on `index.html`) __but__ is not good on the `requirements.html` page.

See screenshot above

![bug](https://raw.githubusercontent.com/dwursteisen/serenity-bug-report/forkmode/bug3.png)

please note that to produce this screenshot, I didn't have any parallel test ! (but multiple test class)

# To Reproduce 

- clone https://github.com/dwursteisen/serenity-bug-report/tree/forkmode on the `forkmode` branch
- `mvn clean install`
- check "Requirements", "Features", "Functional Domains" tabs :  some tests are marked pending

expected result : 

all test are marked are succed, maybe except one that isn't run (`numbers.feature`)

# first through

I try to debug the maven plugin. The issue may be located in the `RequirementsOutcomes` class. When some method are called on this object, from templates file, results don't match my expectation.

**Comment by YamStranger** [comment]
Thanks @dwursteisen for this issue and for debug info!

**Comment by dwursteisen** [comment]
Hello, 

I take some time to understand the issue. 

The problems seems to be in the json generation of test outcomes.

All test are associated with tags, but not all test are associated with the same "logical" tags.

For example, on the reporting, test marked as pending got only one tags : 

```
"tags": [
    {
      "name": "AA scénario",
      "type": "feature"
    }
  ],
```

but the test marked as succed (even if the percentage is wrong) got two tags : 

```
  "tags": [
    {
      "name": "D",
      "type": "Functional Domain"
    },
    {
      "name": "Bla",
      "type": "feature"
    }
  ],
```

And later in the code, Serenity find only this last test, as it's the only one marked with the type "Functional Domain".

I don't know why tags are generated like this, but it may help you. (I think that files are written several times)

**Comment by dwursteisen** [comment]
I haven't found where this json file are created. 

Can you point me where this part of code is located, so I can continue to debug this issue ? It would be great :)

Thanks !

Regards

**Comment by YamStranger** [comment]
@dwursteisen as I remember it should be creaed in https://github.com/serenity-bdd/serenity-core/blob/56b027874e67ebb0bda54959356a2725f5ec91c8/serenity-core/src/main/java/net/thucydides/core/reports/json/JSONTestOutcomeReporter.java

Will take a look

**Comment by dwursteisen** [comment]
Hello, 

We try another way to have some parallel test AND a good serenity reporting. 
To achieve this, we have added some maven profile that will execute only one test class (and several features files) then aggregate everything.

Unfortunately, the reporting is still false. A lot of test are marked as pending instead of OK.
In fact, we never really succed to get a correct reporting using serenity + maven + cucumber. 

Maybe, it's the same issue that still lead to a wrong reporting. Maybe it's because a lot of our tests using accented caracters.

Is there any way to look at this bug or maybe any hint to find a workaround or an easy fix ? (It can fix it but I need some time to understand reporting jsons logic file or where to locking at first). As all our reporting are wrong, we can't use it :sweat:  

To reproduce this bug : 

- clone https://github.com/dwursteisen/serenity-bug-report/tree/aggregate
- go into the module directory
- `mvn install -P a`
- `mvn install -P b`  
- `mvn install -P c`  
- `mvn install -P d`
- `mvn serenity:aggregate`

check the reporting (features tabs, etc)

![img](https://github.com/dwursteisen/serenity-bug-report/raw/aggregate/bug4.png)

**Comment by wakaleo** [comment]
Hi, could you post this sample project? There have been some big changes in the latest code base and I'd like to see if it has fixed this issue.

**Comment by dwursteisen** [comment]
everything is here : https://github.com/dwursteisen/serenity-bug-report (branch forkmode and branch aggregate)

**Comment by wakaleo** [comment]
This should be fixed in the latest releases - could you confirm?

**Comment by dwursteisen** [comment]
I check on my sample project : it works ! 
I still waiting that my team try with this last vestion. I will be able to confirm the fix after.

Regards

**Comment by dwursteisen** [comment]
My team just try it and the feedback is good. So this issue can be closed. Thanks.
