### ISSUE TITLE
Failed to run maven file with sample serenity code.

### ISSUE THREAD

**Issue by Jitendra1665** [serenity-bdd/serenity-maven-plugin#42]
code is attached as the following. I took this from serenity website.
[SprintRunnerBolt.zip](https://github.com/serenity-bdd/serenity-maven-plugin/files/309240/SprintRunnerBolt.zip)

[INFO] 
[INFO] --- serenity-maven-plugin:1.0.47:aggregate (serenity-reports) @ SprintRunnerBolt ---
Reading requirement from directory name C:\Jitendra\MyWork\MyAutoWorkSpace\SprintRunnerBolt\src\test\resources\features\Search
Reading requirement from directory name C:\Jitendra\MyWork\MyAutoWorkSpace\SprintRunnerBolt\src\test\resources\features\shopping_cart
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.335 s
[INFO] Finished at: 2016-06-10T20:18:37+05:30
[INFO] Final Memory: 33M/424M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.0.47:aggregate (serenity-reports) on project SprintRunnerBolt: Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.0.47:aggregate failed. NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by wakaleo** [comment]
This is running an old version of Serenity. Upgrade Serenity to a more recent version (e.g. 1.1.36) and the error should disappear.
