### ISSUE TITLE
Maven plugin error - missing EnvironmentVariables class

### ISSUE THREAD

**Issue by dajester2013** [serenity-bdd/serenity-maven-plugin#44]
I copied the maven POM from the user guide, and tried running `mvn verify`, but got the following error.  I do not have any tests set up yet, but this seems to be failing before even reaching that point.

```
[WARNING] Error injecting: net.serenitybdd.maven.plugins.SerenityAggregatorMojo
java.lang.NoClassDefFoundError: Lnet/thucydides/core/util/EnvironmentVariables;

...

[ERROR] Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.0.47:aggregate (serenity-reports) on project serenity-tests: Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.0.47:aggregate failed: A required class was missing while executing net.serenity-bdd.maven.plugins:serenity-maven-plugin:1.0.47:aggregate: Lnet/thucydides/core/util/EnvironmentVariables;
```

**Comment by wakaleo** [comment]
The versions quoted in the documentation are a bit dated (they will be updated in the next week or so) - the best way to start is to use the maven archetype, as described in this tutorial: http://johnfergusonsmart.com/presentations/serenity-bdd-tutorial-1-introduction-web-testing-serenity-bdd/

**Comment by dajester2013** [comment]
Ah, thank you - I actually just found a demo repo, but I will use the archetypes instead.

**Comment by YamStranger** [comment]
It seems that this ticket is solved. 
For documentation created additional issue - will be fixed soon.
