### ISSUE TITLE
Aggregated reports in maven multi module project

### ISSUE THREAD

**Issue by Invictum** [serenity-bdd/serenity-maven-plugin#47]
I am using Serenity BDD (1.1.34) with jBehave (1.12.0). For execution serenity-maven-plugin (1.1.34) is used.
There is a multi-module maven project. It consists of several modules:
- module A
- module B
- module C

Each module contains full stack of related stuff required for test execution (including defenitions, steps, pages, etc.) Properties are different and defined in serenity.properties files on module level.

To run tests and make a report:

```
clean integration-test serenity:aggregate
```

It work fine when this command is executed in module directory. But when I try to use in on parent POM level I got broken reports:
- module A - /target/site/serenity no index.html
- module B - /target/site/serenity no index.html
- module C - /target/site/serenity no index.html
- parent module - /target/site/serenity index.html is present

I assume for each module separate report should be generated?

**Comment by YamStranger** [comment]
Hello @Invictum 

Please check if index.html in parent directory is correct and contains all tests?

**Comment by Invictum** [comment]
@YamStranger 
It correct, but there are no results here. All resources required for report (images, html, etc) located under modules target.

**Comment by YamStranger** [comment]
@Invictum thanks for your answer. Did you try it with latest version of jbehave, core, junit? Last version can be without this bug

**Comment by Invictum** [comment]
@YamStranger 
Yes I rechecked it with latest version (core - 1.1.37-rc.6, jbehave - 1.13.0, serenity-maven-plugin - 1.1.37-rc.6) and got the same results.
I have created test project for it at git@github.com:Invictum/serenity-multi-module.git

**Comment by YamStranger** [comment]
@Invictum great, thanks!!

**Comment by wakaleo** [comment]
This can be done by placing a relative path to the parent target directory in the serenity.properties file in each module, e.g.

```
serenity.outputDirectory=../target/site/serenity
```
