### ISSUE TITLE
Issue to create short cut to run Maven build

### ISSUE THREAD

**Issue by happyali** [serenity-bdd/serenity-maven-plugin#49]
Hi,
I can run C:\Users*******\Documents\Worksapces\test\MavenDemoSerenity>mvn clean verify
serenity:aggregate -Dwebdriver.driver=firefox from CMD prompt and able to get the result successful along with the serenity report (index.html). 

But when I try to create and run the same cmd from IDE it shows below error message:

[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Sample Serenity project using Cucumber and WebDriver 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.193 s
[INFO] Finished at: 2016-08-29T12:19:46+10:00
[INFO] Final Memory: 5M/77M
[INFO] ------------------------------------------------------------------------
[ERROR] Unknown lifecycle phase "mvn". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhaseNotFoundException

Need your help to create short cut for Maven Build to run this command succussfully and solution for the above issue.

**Comment by happyali** [comment]
I tried mvn clean and mvn install, this result in build successful but no reports are generated. Let me know the step to save Maven build as mentioned above and have a short cut in run configuration for the same.

>mvn clean verify serenity:aggregate -Dwebdriver.driver=firefox

**Comment by wakaleo** [comment]
This is a IDE usage question, rather than a bug, so would be more appropriate for the Serenity BDD Google Group (https://groups.google.com/forum/#!forum/thucydides-users).
