### ISSUE TITLE
History-Page?

### ISSUE THREAD

**Issue by awallat** [serenity-bdd/serenity-maven-plugin#5]
When using Thucydides, I remember that there was a separate history-page that showed a diagram about the progress of the overall tests, like for each day how many tests were pending, successful or failing. Is this report still available in Serenity BDD?

**Comment by wakaleo** [comment]
Hi André,

We dropped that feature in Thucydides a while back, as it was problematic -
there will be an improved history reporting capability for Serenity coming
soon.

Regards

John.

On 13 February 2015 at 04:00, André Wallat <notifications@github.com> wrote:

> When using Thucydides, I remember that there was a separate history-page
> that showed a diagram about the progress of the overall tests, like for
> each day how many tests were pending, successful or failing. Is this report
> still available in Serenity BDD?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-maven-plugin/issues/5>.
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

The dates for the 2014 BDD workshops have been scheduled! Check out our
upcoming *BDD/TDD Master classes*
<http://wakaleo.com/training/testing-and-tdd-for-java-developers> and
our *Advanced
BDD Requirements Workshops
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, coming
soon to *Sydney
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>
*
and *Melbourne
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>!*
___________________________________________________

**Comment by awallat** [comment]
What is the latest status on this? Has this feature been dropped?

**Comment by wakaleo** [comment]
This feature won't be implemented in serenity-core, as it is out of scope for now.

**Comment by williambritt** [comment]
@wakaleo Has this issue/feature been re-prioritized?
