### ISSUE TITLE
Get status of Story in @AfterStory block (JBehave custom StoryReporter)

### ISSUE THREAD

**Issue by oleks-d** [serenity-bdd/serenity-maven-plugin#51]
Hi,

I have to run specific code after execution of story based on story status.
I think using of JBehave @AfterStory will help
Problem is: How to get status of current story execution from @AfterStory?

Looks like solution is implementation of custom StoryReporter (org.jbehave.core.reporters.StoryReporter).

But how to use it in Serenity? 

Thank you for your time!
Alex

**Comment by wakaleo** [comment]
You can try using the Serenity event bus to get the latest test outcome, e.g.
```
        StepEventBus.getEventBus().getBaseStepListener().getTestOutcomes()
```

**Comment by oleks-d** [comment]
Thank you! I will try this approach!
