### ISSUE TITLE
Serenity report indicates fail test when scenario plan is success and compromised

### ISSUE THREAD

**Issue by jpatient** [serenity-bdd/serenity-maven-plugin#53]
To illustrate the title, here some captures :

![unexpected_piechart](https://cloud.githubusercontent.com/assets/13570850/21343966/a8ccea98-c699-11e6-8f66-d9c0768b0557.PNG)

![unexpected_scenarioplan](https://cloud.githubusercontent.com/assets/13570850/21343967/ae0a7e44-c699-11e6-8cff-0e43ef9adecb.PNG)

I wrote a scenario outline with deliberately compromised steps to reproduce the problem.
We can see that the report indicates fail while there are only compromised and succes iterations of the scenario.

**BUT !** (and it's here i think there's something wrong) :
The overall status can change depending of the order of the compromised iterations.
I change the order of the scenario outline and if the last executed iteration is compromised, then the status of the scenario outline is compromised instead of being in error like the first example.

Here are others captures to balance the english explanations of a french developer :)

![expected_piechart](https://cloud.githubusercontent.com/assets/13570850/21344206/dd1259a4-c69a-11e6-9676-f5d8be888639.PNG)

![expected_scenarioplan](https://cloud.githubusercontent.com/assets/13570850/21344209/dfb4d2e0-c69a-11e6-9ddc-9efe4ccac980.PNG)

The problem can be reproduced by checkout a sample project dedicated to the issue :
https://github.com/jpatient/serenity_test
Just checkout the project, run "mvn clean install". Actually, the scenario outline is wrote to reproduce the issue.

**Comment by wakaleo** [comment]
Fixed in 1.2.1-rc.9.
