### ISSUE TITLE
Not able to view aggregation report for Serenity

### ISSUE THREAD

**Issue by NishantSinghh** [serenity-bdd/serenity-maven-plugin#54]
Hi,

I am new to serenity framework I was trying to implement it as I like the reporting of serenity but when I write some sample code and ran it I was not able to view the aggregation report. So I downloaded a sample project written by Mr. Yevhen available on git
[Sample_project](https://github.com/ukrvassabi/serenity-bdd-test)

But still not able to view the aggregation report. Please help me out on this

Regards,
Nishant Singh

**Comment by wakaleo** [comment]
The sample project uses a very old version of serenity. Try using the latest versions.

**Comment by wakaleo** [comment]
Closed for lack of activity
