### ISSUE TITLE
Serenity creates a failed report when working in a maven module

### ISSUE THREAD

**Issue by raphaeldovale** [serenity-bdd/serenity-maven-plugin#6]
I have a multi-module maven project. We are creating a specific module for BDD scenarios and test cases using Serenity and I think I found an issue:

Say I have a module called 'documentation' where I write my stories. If I type something like this:

> mvn verify

or 

> mvn -pl documentation verify

Both commands will create a broken report site where some data will not be presented while the header menu will be incomplete (only "overall test results" and "requirements" are shown). But, if I type the following commands it works:

> cd documentation
> mvn verify

In that case, the data will be correctly presented and also the menu will be built in accordance.

I think the problem is something about the goal serenity:aggregate that, as far as I know, works grouping several data provided by jbehavior and build the reporting site.

**Comment by YamStranger** [comment]
@raphaeldovale thanks for this issue.

Now root cause is clear, and fix will be provided under #22 issue. 

This issue will be closed, as duplicate (to be clear your issue was first, and **thanks a lot for it**, but root cause was find only under #22 issue)

Thanks
