### ISSUE TITLE
Reports not generating with Serenity-bdd 1.0.45

### ISSUE THREAD

**Issue by vbloise3** [serenity-bdd/serenity-maven-plugin#7]
Using serenity-bdd with cucumber. When executing as a junit test within Spring Tool Suite IDE I get the following in the console:

[main] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: TestGEMPortalSteps.the_user_has_permission_to_use_the_GEM_Portal_application - isTheLogonPage
[main] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: isTheLogonPage
[main] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: TestGEMPortalSteps.whenTheUserAttemptsToLogon - entersUserName
[main] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: entersUserName
[main] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: TestGEMPortalSteps.theUserSeesThePasswordScreen - entersSecurityAnswerOrPassword
[main] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: entersSecurityAnswerOrPassword
[main] INFO net.thucydides.core.steps.StepInterceptor - STARTING STEP: TestGEMPortalSteps.theUserShouldSeePortalMainPage - shouldSeeMainPortalPage
[main] INFO net.thucydides.core.steps.StepInterceptor - STEP DONE: shouldSeeMainPortalPage

1 Scenarios ([32m1 passed[0m)
4 Steps ([32m4 passed[0m)
0m20.931s

The test succeeds but no serenity directory is generated under the rarget directory and no report files are generated.

**Comment by YamStranger** [comment]
Hello @vbloise3. 

It should work now. Please check it on last version of serenity bdd. 

If you feel that issue already fixed - please close this issue. 

Thanks a lot!
