### ISSUE TITLE
Report Links broken from 2.2.1 onward when using mvn serenity:aggregate

### ISSUE THREAD

**Issue by ctriebstein** [serenity-bdd/serenity-maven-plugin#82]
We're currently using the sernity-maven-plugin in version 2.1.13 and are suffering from a strange issue when upgrading the maven-serenity-plugin to version 2.2.1 or higher:
When executing `mvn serenity:aggregate` after the serenity tests are executed a report is generated and showing the results of the tests correctly. However when trying to navigate to the detail pages of a specific test the report always tries to open a page with a hash that doesn't exist. The correct report files are in the site folder where the index.html file is generated, files with the hases requested by the report file don't exist anywhere that I could find.

We're using serenity in version 2.3.5 - the bug is reproducable with any version though.

Excerpt from our pom.xml:
 ```
           <dependency>
                <groupId>net.serenity-bdd</groupId>
                <artifactId>serenity-core</artifactId>
                <version>${serenity.version}</version>
            </dependency>

            <dependency>
                <groupId>net.serenity-bdd</groupId>
                <artifactId>serenity-screenplay-rest</artifactId>
                <version>${serenity.version}</version>
            </dependency>

            <dependency>
                <groupId>net.serenity-bdd</groupId>
                <artifactId>serenity-screenplay-webdriver</artifactId>
                <version>${serenity.version}</version>
            </dependency>

            <dependency>
                <groupId>net.serenity-bdd</groupId>
                <artifactId>serenity-junit</artifactId>
                <version>${serenity.version}</version>
            </dependency>

            <dependency>
                <groupId>org.seleniumhq.selenium</groupId>
                <artifactId>selenium-htmlunit-driver</artifactId>
                <version>2.52.0</version>
            </dependency>

...

                          <plugin>
                            <groupId>net.serenity-bdd.maven.plugins</groupId>
                            <artifactId>serenity-maven-plugin</artifactId>
                            <version>${serenity-plugin.version}</version>
                            <executions>
                                <execution>
                                    <id>serenity-reports</id>
                                    <phase>post-integration-test</phase>
                                    <goals>
                                        <goal>aggregate</goal>
                                    </goals>
                                </execution>
                            </executions>
                        </plugin>
```

Are we maybe missing some configuration changes required in newer versions?

**Comment by wakaleo** [comment]
It's probably related to the encoding of the test name. Can you provide a small sample project that reproduces the issue?

**Comment by ctriebstein** [comment]
Well, Ive tried reproducing the issue in a small project but everything seems to be working as intended - I suspect some kind of configuration issue in our project. I'll investigate further and would reopen this ticket if the error is reproducable.
